import mongoose from "mongoose";

const faqSchema = new mongoose.Schema({
  question: String,
  answer: String,
});

const productImageSchema = new mongoose.Schema({
  image: String,
  sortOrder: Number,
sku_code: String
});

const productSchema = new mongoose.Schema({
  id: { type: Number, unique: true },
  vendor_article_name: String,
  category_id: Number,
  vendor_sku_code: String,
  url: String,
  slug: String,
  vendor_article_number: String,
  brand: Number,
  manufacturer_name_and_address_with_pincode: String,
  packer_name_and_address_with_pincode: String,
  importer_name_and_address_with_pincode: String,
  country_of_origin: String,
  weight_kg: Number,
  dimensions_cm: String,
  components: String,
  article_type: String,
  brand_size: String,
  standard_size: String,
  hsn: String,
  sku_code: String,
  age_group: String,
  min_age_years: Number,
  max_age_years: Number,
  product_highlights: String,
  description: String,
  product_benefits: String,
  directions_of_use: String,
  safety_information: String,
  tags: String,
  faqs: [faqSchema],
  product_images: [productImageSchema],
  concern_1: Number,
  concern_2: Number,
  concern_3: Number,
  preference_1: String,
  preference_2: String,
  preference_3: String,
  special_features: String,
  mrp: Number,
  discount_in_percent: Number,
  discount_in_amount: Number,
  final_price: Number,
  status: { type: String, default: "Active" },
  product_id: {type:Number,required:true},
  new_arrival: Number,
  top_picks: Number,
  ranking: Number,
  toppics_ranking: Number,
  newarrival_ranking: Number,
  expires_in_days: Number,
  key_ingredients: String,
  other_ingredients: String,
  min_order_quantity: Number,
  max_order_quantity: Number,
  back_order_quantity: Number,
  meta_title: String,
  meta_description: String,
  stock_status: String,
  product_video: String,
  expert_advice: String,
  specifications: String,
  feeding_table: String,
  size_chart: String,
  skin_type: String,
  hair_type: String,
  spf_type: String,
  size_chart_type: String,
  color: String,
  flavour: String,
  protein_type: String,
  diaper_style: String,
  formulation_type: String,
  staging: String,
  checkout: { type: String, default: "NO" },
  style_group_id: Number,
  show_stock: Number,
  sub_category_id: Number,
  sub_sub_category_id: Number,
  sub_sub_sub_category_id: Number,
}, { timestamps: true });

export default mongoose.model("Product", productSchema);
