export const userType = {
  USER: "user",
  ADMIN: "admin",
};
export const orderPlacedStatus = {
  PLACED: "PLACED",
  PENDING: "PENDING",
  FAILED: "FAILED",
};

export const status = {
  active: "Active",
  inActive: "In-Active",
};

export const requiredColumnsForProductsExcelFile = [
  "product_id",
  "category",
  "sub_category",
  "sub_sub_category",
  "sub_sub_sub_category",
  "brand",
  "vendor_article_name",
  "description",
  "mrp",
  "style_group_id",
  "vendor_sku_code",
  "vendor_article_number",
  "manufacturer_name_and_address_with_pincode",
  "packer_name_and_address_with_pincode",
  "importer_name_and_address_with_pincode",
  "country_of_origin",
  "weight_kg",
  "dimensions_cm",
  "components",
  "expires_on_or_after_dd_mm_yyyy",
  "article_type",
  "brand_size",
  "standard_size",
  "hsn",
  "sku_code",
  "age_group",
  "min_age_years",
  "max_age_years",
  "product_highlights",
  "product_benefits",
  "directions_of_use",
  "safety_information",
  "tags",
  "added_date",
  "skin_type",
  "hair_type",
  "spf",
  "size_chart",
  "colours",
  "flavours",
  "protein_type",
  "diaper_style",
  "staging",
  "accessories_specification",
  "feeding_table",
  "concern_1",
  "concern_2",
  "concern_3",
  "slug",
  "total_shelf_life_in_months",
  "minimum_usable_period_in_months",
  "minimum_shelf_life_in_months",
  "sustainable",
  "key_ingredients",
  "preference",
  "preference_2",
  "preference_3",
  "formulation",
  "type",
  "net_weight",
  "special_features",
  "how_to_apply",
  "other_ingredients",
  "quantity_in_gram_gm",
  "quantity_in_ml_ml",
  "quantity_in_pieces_pc",
  "expert_advice",
  "faq1",
  "faq1_a",
  "faq2",
  "faq2_a",
  "faq3",
  "faq3_a",
  "faq4",
  "faq4_a",
  "faq5",
  "faq5_a",
  "faq6",
  "faq6_a",
  "faq7",
  "faq7_a",
  "front_image",
  "side_image",
  "back_image",
  "detail_angle",
  "look_shot_image",
  "additional_image_1",
  "additional_image_2",
  "expires_in_days",
  "meta_title",
  "meta_description",
  "checkout",
  "url",
  "ranking",
  "top_picks",
  "toppics_ranking",
  "new_arrival",
  "newarrival_ranking"
];

export const requiredColumnsForProductImagesExcelFile = [
  "product_id",
  "sku_code",
  "image",
  "sortOrder"
];

export const requiredColumnsForProductPricesExcelFile = [
  "product_id",
  "sku_code",
  "mrp",
  "discount_amount",
  "discount_percentage",
]

export const requiredColumnsForOfferProductExcelFile = [
  "product_id",
  "sku_code",
];